apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image | required "image is required "}}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: MY_APP_API_BASE_URL
              value: friends-app-backend/api
      imagePullSecrets:
        - name: {{ .Values.dockerConfigJson.secretName }}
