apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer #Have to keep for test purposes without ingress controller
  selector:
    app: {{ .Release.Namespace }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
